"""Test analytics — top tests performed, orders per test."""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass
from typing import Optional

from . import get_connection, paise_to_rupees


@dataclass
class TestStat:
    """Statistics for a single test."""

    test_id: int
    test_name: str
    order_count: int
    total_revenue: float
    is_active: bool


def get_top_tests(
    conn: Optional[sqlite3.Connection] = None,
    limit: int = 10,
    months: int = 12,
) -> list[TestStat]:
    """Return the most-ordered tests in the last *months* months.

    Ranked by order count descending.  Includes revenue generated by each test.
    """
    close_conn = conn is None
    if close_conn:
        conn = get_connection()

    try:
        rows = conn.execute(
            """
            SELECT
                ot.test_id,
                IFNULL(ot.test_name_snapshot, t.name) AS test_name,
                COUNT(DISTINCT ot.order_id) AS order_count,
                SUM(ot.price_paise) AS total_paise,
                IFNULL(t.is_active, 1) AS is_active
            FROM order_tests ot
            JOIN orders o ON o.id = ot.order_id
            LEFT JOIN tests t ON t.id = ot.test_id
            WHERE o.created_at >= DATE('now', ?)
            GROUP BY ot.test_id, test_name
            ORDER BY order_count DESC
            LIMIT ?
            """,
            (f"-{months} months", limit),
        ).fetchall()

        return [
            TestStat(
                test_id=row["test_id"],
                test_name=row["test_name"],
                order_count=row["order_count"],
                total_revenue=paise_to_rupees(row["total_paise"]),
                is_active=bool(row["is_active"]),
            )
            for row in rows
        ]
    finally:
        if close_conn:
            conn.close()


def get_all_time_top_tests(
    conn: Optional[sqlite3.Connection] = None,
    limit: int = 10,
) -> list[TestStat]:
    """Return the most-ordered tests of all time."""
    close_conn = conn is None
    if close_conn:
        conn = get_connection()

    try:
        rows = conn.execute(
            """
            SELECT
                ot.test_id,
                IFNULL(ot.test_name_snapshot, t.name) AS test_name,
                COUNT(DISTINCT ot.order_id) AS order_count,
                SUM(ot.price_paise) AS total_paise,
                IFNULL(t.is_active, 1) AS is_active
            FROM order_tests ot
            LEFT JOIN tests t ON t.id = ot.test_id
            GROUP BY ot.test_id, test_name
            ORDER BY order_count DESC
            LIMIT ?
            """,
            (limit,),
        ).fetchall()

        return [
            TestStat(
                test_id=row["test_id"],
                test_name=row["test_name"],
                order_count=row["order_count"],
                total_revenue=paise_to_rupees(row["total_paise"]),
                is_active=bool(row["is_active"]),
            )
            for row in rows
        ]
    finally:
        if close_conn:
            conn.close()


def get_total_tests_count(conn: Optional[sqlite3.Connection] = None) -> int:
    """Return the total number of active tests in the catalog."""
    close_conn = conn is None
    if close_conn:
        conn = get_connection()

    try:
        row = conn.execute(
            "SELECT COUNT(*) AS cnt FROM tests WHERE is_active = 1"
        ).fetchone()
        return row["cnt"] if row else 0
    finally:
        if close_conn:
            conn.close()


def get_total_orders_count(conn: Optional[sqlite3.Connection] = None) -> int:
    """Return the total number of orders."""
    close_conn = conn is None
    if close_conn:
        conn = get_connection()

    try:
        row = conn.execute("SELECT COUNT(*) AS cnt FROM orders").fetchone()
        return row["cnt"] if row else 0
    finally:
        if close_conn:
            conn.close()